### ISSUE TITLE
No dev branch

### ISSUE THREAD

**Issue by JimJamUrCode** [iamjake648/jasper-dictionary#2]
Right now on the jasper repo, there is a jasper-dev branch that has a lot of great updates. From my experience, the format that this plugin is currently using, is not compatible with jasper-dev. I have created a version of this module that works with the jasper-dev branch. I do not want to make a pull request onto the master branch of this repo. Is there anyway a dev branch could be created so that I can make a pull request?

**Comment by iamjake648** [comment]
Added
